baseurl: ''
exclude: ['README.md']
permalink: /:title/
title: 'NVM Projects & Solutions'

collections:
  services:
    output: true
    permalink: /services/:title/
  team:
    output: true
    permalink: /team/:title/
  testimonials:
    output: true
    permalink: /testimonials/:title/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
  
plugins:
  - jekyll-sitemap